### ISSUE TITLE
Error running make search-report

### ISSUE THREAD

**Issue by Oysterclam** [UCSD-PL/proverbot9001#25]
Following advice I was given, I removed line 15 from proverbot9001/dataloader/dataloader-core/Cargo.toml in order to get `make setup` to finish running

`features = ["extension-module"]`

After that, I get errors when trying to run `make search-report`

```
MacBook-Pro-4:proverbot9001 andyyang$ make search-report
(export LD_LIBRARY_PATH=/usr/local/cuda/lib64/:$LD_LIBRARY_PATH ; cat data/compcert-test-files.txt | cat | \
	xargs ./src/proverbot9001.py search-report -j 16 --weightsfile=data/polyarg-weights.dat --prelude=./CompCert --search-depth=6 --search-width=5 -P )
Traceback (most recent call last):
  File "./src/proverbot9001.py", line 26, in <module>
    import search_file
  File "/Users/andyyang/Desktop/proverbot9001/src/search_file.py", line 41, in <module>
    from predict_tactic import (static_predictors, loadPredictorByFile,
  File "/Users/andyyang/Desktop/proverbot9001/src/predict_tactic.py", line 49, in <module>
    from models import features_polyarg_predictor
  File "/Users/andyyang/Desktop/proverbot9001/src/models/features_polyarg_predictor.py", line 45, in <module>
    from dataloader import (features_polyarg_tensors,
ImportError: cannot import name 'encode_fpa_stem' from 'dataloader' (/Users/andyyang/Desktop/proverbot9001/src/dataloader.py)
make: *** [search-report] Error 1

```
Upon inspection, it doesn't seem that `encode_fpa_stem` is inside the file `dataloader.pyi` at all. Was anyone able to resolve any similar errors? Any help is appreciated!

**Comment by Oysterclam** [comment]
Upon working through some pyo3 tutorials I found I needed to copy the `libdataloader.dylib` generated in the release folder into an `dataloader.so` file, which can be opened by python. In addition to deleting the line mentioned in my earlier comment, I modified the makefile to do this: 

```
src/dataloader.so: $(DATALOADER_SRC) dataloader/dataloader.pyi
	cd dataloader && rustup run nightly cargo build --release --no-default-features
	cp dataloader/target/release/libdataloader.dylib src/dataloader.so

```

Now, I am only getting errors with serapy

`coq_serapy.CoqExn: Unable to locate library Coqlib`

**Comment by Oysterclam** [comment]
The above issues were resolved. However, after `make search-report` and letting it run for many hours, it decided to stop at 501/507 for unknown reasons. Has anyone else experienced this?

```

 99%|█████████████████████████████████████████████████▍| 501/507 [12:15:54<2:42:04, 1620.68s/it]

                                                                                                
                                                                                                
alloc_global_exists:   1%|▌                                                 | 1054/97655 [03:52]
                                                                                                
                                                                                                
sem_cmp_inj:  23%|████████████▋                                          | 22548/97655 [6:33:14]
store_init_data_list_m...:   1%|▍                                           | 1096/97655 [01:19]
init_mem_transf:   2%|▉                                                     | 1796/97655 [01:40]
                                                                                                
                                                                                                
alloc_globals_match:   8%|███▊                                              | 7420/97655 [08:33]
alloc_globals_match:   5%|██▌                                               | 4958/97655 [06:21]
                                                                                                
find_funct_transf:   1%|▎                                                    | 634/97655 [00:36]
sem_cmp_inj:  27%|██████████████▊                                        | 26348/97655 [7:05:59]
find_var_info_match:   1%|▌                                                 | 1180/97655 [03:57]
init_mem_transf_partial:   3%|█▍                                            | 3138/97655 [03:01]
sem_cmp_inj:  24%|████████████▉                                          | 23002/97655 [6:38:29]
store_init_data_exists:   3%|█▏                                             | 2504/97655 [12:54]

find_funct_ptr_transf:   1%|▏                                                | 494/97655 [00:26]
find_funct_transf:   1%|▎                                                    | 574/97655 [00:30]
find_var_info_match:   2%|█▏                                                | 2432/97655 [07:33]
sem_binary_operation_inj:  18%|███████▌                                  | 17712/97655 [6:08:46]
find_var_info_match:   1%|▍                                                  | 930/97655 [03:22]
find_funct_transf_partial:   1%|▍                                            | 940/97655 [02:02]
find_funct_ptr_match:   1%|▎                                                 | 620/97655 [02:54]

store_init_data_exists:   4%|██                                             | 4162/97655 [19:45]

store_init_data_list_e...:   0%|▏                                            | 464/97655 [03:58]
```

**Comment by HazardousPeach** [comment]
I'm going to  close this issue since I Haven't heard anything back about more debugging efforts, but feel free to reopen if it's still an issue.
